// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;

// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }

//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyBCKAfwuXbXCkD-Ce1dwWvP1fDZoRQzIQ4',
//     appId: '1:306319549768:android:c76c8a797fb2c8096aff7d',
//     messagingSenderId: '306319549768',
//     projectId: 'mushroom-monitoring-database',
//     databaseURL: 'https://mushroom-monitoring-database-default-rtdb.europe-west1.firebasedatabase.app',
//     storageBucket: 'mushroom-monitoring-database.appspot.com',
//   );

//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCmDZedd1DpWWXnrAmrJP2enDogiiRHbrs',
//     appId: '1:306319549768:ios:66e0f6cc53d829316aff7d',
//     messagingSenderId: '306319549768',
//     projectId: 'mushroom-monitoring-database',
//     databaseURL: 'https://mushroom-monitoring-database-default-rtdb.europe-west1.firebasedatabase.app',
//     storageBucket: 'mushroom-monitoring-database.appspot.com',
//     iosBundleId: 'com.mushroommonitoring.app.testProject',
//   );

// }